import "../styles/packages.css";
import { Link, useNavigate, useLocation } from "react-router-dom";

function ProductAnalysis() {
  const navigate = useNavigate();
  const location = useLocation();
  const product = location.state?.product;

  const handleNext = () => {
    if (!product) {
      navigate("/app/product-details");
      return;
    }
    navigate("/app/manual-entry", { state: { product } });
  };

  return (
    <div className="page-wrapper">
      <h1 className="page-title">Product Analysis</h1>

      <div className="analysis-card">
        <h2 className="section-title">Auto-Extracted Product Details</h2>

        {!product ? (
          <p className="analysis-text error">
            No product data found. Please analyze again.
          </p>
        ) : (
          <div className="analysis-grid">
            <div className="analysis-item">
              <span className="label">Product Name:</span>
              <span className="value">{product.name}</span>
            </div>

            <div className="analysis-item">
              <span className="label">Dimensions:</span>
              <span className="value">{product.dimensions}</span>
            </div>

            <div className="analysis-item">
              <span className="label">Weight:</span>
              <span className="value">{product.weight}</span>
            </div>

            <div className="analysis-item">
              <span className="label">Fragility:</span>
              <span className="value">{product.fragility}</span>
            </div>

            <div className="analysis-item">
              <span className="label">Category:</span>
              <span className="value">{product.category}</span>
            </div>
          </div>
        )}

        <div className="analysis-actions">
          <Link to="/app/product-details" className="btn-outline">
            ← Back
          </Link>

          <button className="btn-primary" onClick={handleNext}>
            Proceed to Recommendations →
          </button>
        </div>
      </div>
    </div>
  );
}

export default ProductAnalysis;

/*import "../styles/packages.css";
import { Link, useNavigate } from "react-router-dom";

function ProductAnalysis() {
  const navigate = useNavigate();

  const handleNext = () => {
    navigate("/app/Manual-Entry");
  };

  return (
    <div className="page-wrapper">
      <h1 className="page-title">Product Analysis</h1>

      <div className="analysis-card">
        <h2 className="section-title">Auto-Extracted Product Details</h2>

        <p className="analysis-text">These values are auto-generated by Computer Vision (placeholder demo).</p>

        <div className="analysis-grid">
          <div className="analysis-item">
            <span className="label">Product Type:</span>
            <span className="value">Bottle (placeholder)</span>
          </div>

          <div className="analysis-item">
            <span className="label">Estimated Dimensions:</span>
            <span className="value">25 × 10 × 10 cm</span>
          </div>

          <div className="analysis-item">
            <span className="label">Approx. Weight:</span>
            <span className="value">0.5 kg</span>
          </div>

          <div className="analysis-item">
            <span className="label">Fragility Level:</span>
            <span className="value">Medium</span>
          </div>

          <div className="analysis-item">
            <span className="label">Category:</span>
            <span className="value">Plastic</span>
          </div>
        </div>

        <div className="analysis-actions">
          <Link to="/product-details" className="btn-outline">← Back</Link>

          <button className="btn-primary" onClick={handleNext}>
            Proceed to Recommendations →
          </button>
        </div>
      </div>
    </div>
  );
}

export default ProductAnalysis;*/
