import "../styles/packages.css";
import { Link, useNavigate } from "react-router-dom";

function ProductAnalysis() {
  const navigate = useNavigate();

  const handleNext = () => {
    navigate("/recommendations");
  };

  return (
    <div className="page-wrapper">
      <h1 className="page-title">Product Analysis</h1>

      <div className="analysis-card">
        <h2 className="section-title">Auto-Extracted Product Details</h2>

        <p className="analysis-text">These values are auto-generated by Computer Vision (placeholder demo).</p>

        <div className="analysis-grid">
          <div className="analysis-item">
            <span className="label">Product Type:</span>
            <span className="value">Bottle (placeholder)</span>
          </div>

          <div className="analysis-item">
            <span className="label">Estimated Dimensions:</span>
            <span className="value">25 × 10 × 10 cm</span>
          </div>

          <div className="analysis-item">
            <span className="label">Approx. Weight:</span>
            <span className="value">0.5 kg</span>
          </div>

          <div className="analysis-item">
            <span className="label">Fragility Level:</span>
            <span className="value">Medium</span>
          </div>

          <div className="analysis-item">
            <span className="label">Category:</span>
            <span className="value">Plastic</span>
          </div>
        </div>

        <div className="analysis-actions">
          <Link to="/product-details" className="btn-outline">← Back</Link>

          <button className="btn-primary" onClick={handleNext}>
            Proceed to Recommendations →
          </button>
        </div>
      </div>
    </div>
  );
}

export default ProductAnalysis;
